*** Settings ***
Library    RequestsLibrary
Library    String


*** Keywords ***
Criar um usuário novo
    ${palavra_aleatoria}    Generate Random String    length=4    chars=[LETTERS]
    ${palavra_aleatoria}    Convert To Lower Case    string
    # Log    Minha palavra aleatória: ${palavra_aleatoria}@emailteste.com
    Set Test Variable    ${EMAIL_TEST}    ${palavra_aleatoria}@emailteste.com
    Log    ${EMAIL_TEST}

Cadastrar o usuário criado na ServeRest
    ${body}    Create Dictionary    
    ...    nome=Fulano da Silva    
    ...    email=${EMAIL_TEST}    
    ...    password=1234    
    ...    administrador=true
    
    Log    ${body}

    Criar Sessão na ServeRest
    ${resposta}    POST On Session    
    ...    alias=ServeRest    
    ...    url=/usuarios
    ...    json=${body}
    
    Log    ${resposta.json()}
    
Criar Sessão na ServeRest
    ${headers}    Create Dictionary    accept=application/json    Content-Type=application/json
    Create Session    alias=ServeRest    url=https://serverest.dev    headers=${headers}



